name: Good practices in CI/CD

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build
        
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Эта строка гарантирует, что deploy запускается только после успешного завершения build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      - name: Deploy application
        run: ./deploy.sh
